@startuml
title "Git Transport Diagram"

participant Worktree
participant Index
participant "Local Repository" as Local
participant "Remote Repository" as Remote

Worktree -> Index   : add
Index -> Worktree   : restore --staged
Index -> Local      : commit
Local -> Worktree   : restore --source
Local -> Remote     : push
Remote -> Local     : fetch
Local -> Worktree   : merge
Remote -> Worktree  : pull

@enduml

