@startuml

'Configuration
skinparam lifelineStrategy solid
skinparam backgroundColor #EEEBDC
skinparam handwritten true

'Participants
participant Master
participant Branch

'Diagram
[-> Branch          : branch
Master ->o Branch   : switch
Branch -->o Branch  : add
Branch -->o Branch  : test
Branch -->o Branch  : commit
Branch ->o Master   : switch
Branch ->o Master   : merge

...

@enduml