@startuml
title "Git Transport Diagram"

participant Workspace
participant Index
participant "Local Repository" as Local
participant "Remote Repository" as Remote

Workspace -> Index  : add
Index -> Workspace  : restore --staged
Index -> Local      : commit
Local -> Workspace  : restore --source
Local -> Remote     : push
Remote -> Local     : fetch
Local -> Workspace  : merge
Remote -> Workspace : pull

@enduml

