@startuml
skinparam lifelineStrategy solid
'skinparam backgroundColor #EEEBDC
skinparam handwritten true

participant Workspace
participant Index
participant "Local Repository" as Local
participant "Remote Repository" as Remote

'Initialization
Remote -> Remote    : git init --bare demo.git
note left
    Creates the git folder
end note

'Cloning
Remote -> Workspace : git clone demo.git
note right
    Copies the git folder
    and populates the project
    folder with the latest
    version of the project files
end note

'Work in progress
Workspace -> Workspace : Create files
note left
    The developer works
    in the project folder
end note

'Staging
Workspace -> Index  : git add *
note left
    Add files or changes
    to the staging area
end note

'Unstaging
Index -> Workspace  : git restore *
note right
    Revert changes to files
    in the working tree
end note

'Commit
Index -> Local      : git commit -m 'Message'
note left
    Save the changes to the
    commit history
end note

'Reverting
Local -> Index  :  restore * --staged
note right
    Revert changes in
    the index file
end note

'Pushing
Local -> Remote     : git push
note left
    Copy the commit history
    from the local repository
    to the remote repository
end note

'Fetching
Remote -> Local     : git fetch
note right
    Copy the commit history
    from the remote repository
    to the local repository
end note

'Update
Local -> Workspace  : git merge
note right
    Update the working files
    using the commit history
end note

'Pulling
Remote -> Workspace : git pull
note right
   Fetch and merge
end note

@enduml

