@startuml
skinparam lifelineStrategy solid
skinparam ParticipantPadding 10
skinparam BoxPadding 5

box Local #LightYellow
participant "Local\nmain" as Local #White
participant "Local\nhotfix" as Hotfix #White
end box

box Remote #LightGreen
participant "Remote\nmain" as Remote #White
end box

'skinparam backgroundColor #EEEBDC
'skinparam handwritten true


== Setup ==
Remote -> Remote: init
Remote -> Local: clone

== Development ==
Remote -> Local: pull
Local -> Local: add
Local --> Local: test
Local -> Local: commit
Local -> Remote: push

[-> Local: tag
note right: V0.0.0.Sprint
...
Local -> Remote: push --tags

== Test ==

[-> Local: tag
note right: V1.0.0.A
Remote -> Local: pull
Local --> Local: test
Local -> Local: commit
Local -> Remote: push

[-> Local: tag
note right: V1.0.0.B
Remote -> Local: pull
Local --> Local: test
Local -> Remote: push

== Release ==
[-> Local: tag
note right: V1.0.0
Local -> Remote: push

== Development ==
Remote -> Local: pull
Local -> Local: add
Local -> Local: test
Local -> Local: commit

[-> Local: tag
note right: V1.0.0.Sprint
...
Local -> Remote: push


== Hotfix ==
Remote -> Local: pull
...

[-> Hotfix: branch from tag V1.0.0
Local ->o Hotfix: switch
Hotfix ->o Hotfix: add
Hotfix -->o Hotfix: test
Hotfix ->o Hotfix: commit
Hotfix ->o Local: switch
Hotfix ->o Local: merge
[-> Local: tag
note right: V1.0.1

Local -> Local: add
Local --> Local: test
Local -> Local: commit
...
[-> Local: tag
note right: V1.0.1.Sprint
Local -> Remote: push
@enduml
