@startuml

'Configuration
skinparam lifelineStrategy solid
skinparam backgroundColor #EEEBDC
skinparam handwritten true

'Participants
participant Master
participant Develop

'Diagram
[-> Develop             : branch
Master ->o Develop      : switch
Develop ->o Develop     : add
Develop ->o Develop     : commit
Develop ->o Master      : switch
Develop ->o Master      : merge

...

@enduml