@startuml
skinparam lifelineStrategy solid
'skinparam backgroundColor #EEEBDC
skinparam handwritten true
participant "Local Master" as Local
participant "Remote Master" as Remote
participant "Local Hotfix" as Hotfix

== Setup ==
Remote -> Remote: init
Remote -> Local: clone

== Development ==
Remote -> Local: pull
Local -> Local: add
Local --> Local: test
Local -> Local: commit

[-> Local: tag
note right: 0.0.0.Issue
...
Local -> Remote: push

== Test ==

[-> Local: tag
note right: 1.0.0.A
Remote -> Local: pull
Local --> Local: test
Local -> Local: commit
Local -> Remote: push

[-> Local: tag
note right: 1.0.0.B
Remote -> Local: pull
Local --> Local: test
Local -> Remote: push

== Release ==
[-> Local: tag
note right: 1.0.0
Local -> Remote: push

== Development ==
Remote -> Local: pull
Local -> Local: add
Local -> Local: test
Local -> Local: commit

[-> Local: tag
note right: 1.0.0.Issue
...
Local -> Remote: push


== Hotfix ==
Remote -> Local: pull
...

[-> Hotfix: branch
Local ->o Hotfix: switch
Hotfix ->o Hotfix: add
Hotfix -->o Hotfix: test
Hotfix ->o Hotfix: commit
Hotfix ->o Local: switch
Hotfix ->o Local: merge
[-> Local: tag
note right: 1.0.1

Local -> Local: add
Local --> Local: test
Local -> Local: commit
...
[-> Local: tag
note right: 1.0.1.Issue
Local -> Remote: push
@enduml
