@startuml
skinparam lifelineStrategy solid
'skinparam backgroundColor #EEEBDC
skinparam handwritten true

participant Workspace
participant Index
participant "Local Repository" as Local
participant "Remote Repository" as Remote

Remote -> Remote    : init
Remote -> Local     : clone
Workspace -> Index  : add
Index -> Workspace  : reset
Index -> Local      : commit
Local -> Workspace  : restore
Local -> Remote     : push
Remote -> Local     : fetch
Local -> Workspace  : merge
Remote -> Workspace : pull

@enduml

