@startuml

'Configuration
skinparam lifelineStrategy solid
'skinparam backgroundColor #EEEBDC
skinparam handwritten true

'Participants
participant Master
participant Branch
participant Tag

'Diagram
[-> Branch             : branch
Master  ->o Branch     : switch
Master  ->o Tag        : switch
Branch  ->o Branch     : add
Tag     ->o Tag        : add
Branch  ->o Branch     : commit
Tag     ->o Tag        : commit
Tag     ->o Tag        : tag
Branch  ->o Master     : switch
Tag     ->o Master     : switch
Branch  ->o Master     : merge
Tag     ->o Master     : merge
...

@enduml